spring:
  application:
    name: backend
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  management:
    endpoints:
      web:
        exposure:
          include: health,info

logging:
  level:
    root: INFO

jahez:
  base-url: ${JZ_BASE_URL}
  secret: ${JZ_SECRET}
  api-key: ${JZ_X_API_KEY}
  clock-skew-seconds: 60
  connect-timeout-ms: 3000
  read-timeout-ms: 5000


tiktok:
  access-token: ${TIKTOK_ACCESS_TOKEN}
  pixel-code: ${PIXEL_CODE}
  tiktok-endpoint: ${TIKTOK_ENDPOINT}

server:
  error:
    include-message: always